import type {
  AssistantModelMessage,
  ModelMessage,
  ToolModelMessage,
  UserModelMessage,
} from "ai";
import type {
  ContextPrepareInput,
  ContextRetentionOptions,
  ConversationRetentionEvent,
} from "./retention/retention.types";

export type {
  AssistantModelMessage,
  ModelMessage,
  ToolModelMessage,
  UserModelMessage,
} from "ai";
export type {
  CompactionOptions,
  ContextPrepareInput,
  ContextRecordTransform,
  ContextRetentionOptions,
  ContextTransformInput,
  ConversationRetentionEvent,
  RollingWindowOptions,
  SummarizeRecords,
} from "./retention/retention.types";

export type ResponseMessage = AssistantModelMessage | ToolModelMessage;

/**
 * Whether a record is part of the agent's effective (LLM-visible) context.
 * `superseded` records are retained for export/audit but excluded from the
 * message projection.
 */
export type ConversationRecordStatus = "active" | "superseded";

export interface ConversationUsage {
  /** Tokens used by the prompt/input side of the agent call. */
  readonly promptTokens: number;
  /** Tokens generated by the model output side of the agent call. */
  readonly completionTokens: number;
}

export interface ContextUsage {
  /** Tokens occupying the final model step's context window. */
  readonly totalTokens: number;
  /** Input tokens in the final model step, when reported. */
  readonly inputTokens?: number;
  /** Output tokens in the final model step, when reported. */
  readonly outputTokens?: number;
  /** Detailed input-token categories reported by the model provider. */
  readonly inputTokenDetails?: {
    readonly noCacheTokens?: number;
    readonly cacheReadTokens?: number;
    readonly cacheWriteTokens?: number;
  };
  /** Detailed output-token categories reported by the model provider. */
  readonly outputTokenDetails?: {
    readonly textTokens?: number;
    readonly reasoningTokens?: number;
  };
}

export interface ConversationRecord {
  /** Stable identifier for this single agent call record. */
  readonly id: string;
  /** Agent that owns this context record. */
  readonly agentName: string;
  /** ISO timestamp for when the record was created. */
  readonly createdAt: string;
  /** User message sent to the agent for this call. */
  readonly userMessage: UserModelMessage;
  /** Assistant and tool messages returned by the AI SDK for this call. */
  readonly responseMessages: readonly ResponseMessage[];
  /** Final text returned by the agent. */
  readonly text: string;
  /** Exact token usage reported by the provider for this call. */
  readonly usage: ConversationUsage;
  /** Final model-step context usage. */
  readonly contextUsage?: ContextUsage;
  /** Provider finish reason for this call. */
  readonly finishReason: string;
  /**
   * Whether this record feeds the agent's effective context.
   * @default "active"
   */
  readonly status?: ConversationRecordStatus;
  /** Id of the summary record that replaced this one, when superseded. */
  readonly supersededBy?: string;
}

export interface CreateConversationRecordInput {
  /** Stable identifier for this record. Defaults to a random UUID. */
  readonly id?: string;
  /** Agent that owns this context record. */
  readonly agentName: string;
  /** Creation timestamp. Defaults to the current time. */
  readonly createdAt?: string;
  /** User input sent to the agent. */
  readonly userMessage: string | UserModelMessage;
  /** Assistant and tool messages returned by the AI SDK for this call. */
  readonly responseMessages: readonly ResponseMessage[];
  /** Final text returned by the agent. */
  readonly text: string;
  /** Exact token usage reported by the provider for this call. */
  readonly usage: ConversationUsage;
  /** Final model-step context usage. */
  readonly contextUsage?: ContextUsage;
  /** Provider finish reason for this call. */
  readonly finishReason: string;
}

export interface ConversationHistory {
  /** Ordered conversation records across the run. */
  readonly records: readonly ConversationRecord[];
  /** Retention events that changed the effective model context. */
  readonly retentionEvents: readonly ConversationRetentionEvent[];
}

/** Options for {@link createConversationContext}. */
export type ConversationContextOptions = ContextRetentionOptions;

export interface ConversationContext {
  readonly length: number;
  readonly isEmpty: boolean;
  appendRecord(record: ConversationRecord): void;
  records(agentName?: string): readonly ConversationRecord[];
  messages(agentName?: string): readonly ModelMessage[];
  /** Prepare records before a model call by applying configured retention. */
  prepareForCall(
    input: ContextPrepareInput,
  ): Promise<readonly ConversationRetentionEvent[]>;
  importRecords(records: readonly ConversationRecord[]): void;
  exportRecords(): readonly ConversationRecord[];
  importJsonl(jsonl: string): void;
  exportJsonl(): string;
  importJson(json: string): void;
  exportJson(): string;
  importYaml(yaml: string): void;
  exportYaml(): string;
  clear(): void;
  [Symbol.iterator](): Iterator<ConversationRecord>;
}
