export const DEFAULT_DAEMON_READY_TIMEOUT_MS = 3000;
export const DEFAULT_DAEMON_STOP_TIMEOUT_MS = 5000;
export const DAEMON_POLL_INTERVAL_MS = 200;
export const FALLBACK_DAEMON_VERSION = "2.0.0-rc.0";
